### ISSUE TITLE
Channel mode to block notices

### ISSUE THREAD

**Issue by eaescob** [DALnet/bahamut#34]
Request from dalnet-src@ to add a channel mode that blocks notices except from those who are AOP/SOP/Founder lists.

**Comment by Alsjman** [comment]
I believe when they do so there must be reasons behind that. but since it's just to block notice i think its useless request

**Comment by Pintuzoft** [comment]
The ircd is handling a channel message and channel notice the same way I think, it seem to just be flagged as a notice if its a notice(?). Among irc clients however it seem to be very common to treat a message and a notice differently making them look different from eachother, color them differently and even some clients is set to play a sound when a channel notice is parsed by default. So eventhough they are essentially the same for the server, the end user is persieving them as completely different. Its in that sense I think giving channel ops the ability to filter them out might be useful. Ofc I guess it would suffice making it about +ov vs -ov.

The +M is excellent, though different channels and different ops have their preferable ways to moderate a chat and as h noted some users would consider avoiding +M to not kill the chat in a channel where there is alot of new/unidentified users. 

Another thought I had about this recently is that perhaps it should be inverted kinda, so instead of blocking channel notices it perhaps rather should only allow normal messages in the channel?, this would in that case not only filter out channel notices but actions and perhaps ctcp sent to the channel aswell?.

**Comment by eaescob** [comment]
I still don't see the use case for when this is needed. If the fear is notice floods, then setting the channel to only allow registered nicks should minimize the impact/chances of this.

**Comment by Pintuzoft** [comment]
ah ok, thanks for taking your time to consider it though :)

**Comment by kobishmueli** [comment]
Closing this as we have added similar feature that can prevent channel notices (#41).

Kobi.
